### PR TITLE
Use Python f-string to ease the cat herding

### PR DESCRIPTION
**Pull request by cclauss**
Cool project!

### CODE REVIEW

**Comment by AlexiaJM** [comment]
Nice small changes, I hadn't seen f-strings before, it's cleaner. Can you make those small changes also in the other GAN files, it shouldn't take long. Then, I'll approve your pull request.

**Comment by cclauss** [comment]
Ready for review.

**Comment by AlexiaJM** [comment]
Tested and it's all good! Thanks!

**Comment by AlexiaJM** [comment]
Sorry I have to merge before closing....

**Pull request merged**
